# Configuration ChaseHound pour CI/CD
# Paramètres optimisés pour l'exécution automatisée sur GitHub Actions

chasehound:
  # Paramètres de date pour l'analyse
  start_date: "2024-01-01"  # Début de l'année en cours
  end_date: "2024-12-31"    # Fin de l'année en cours
  
  # Filtres fondamentaux (plus permissifs pour CI)
  lowest_market_gap: 10000000      # 10M au lieu de 50M
  lowest_avg_turnover: 10000000    # 10M au lieu de 20M
  lowest_avg_turnover_days: 10     # Réduit de 20 à 10 jours
  lowest_price: 1.0                # Prix minimum plus bas
  latest_report_date_days: 180     # Plus permissif (6 mois)
  
  # Filtres de volatilité
  turnoverSpikeThreshold: 1.02     # Seuil plus bas
  turnoverShortTermDays: 3         # Période plus courte
  turnoverLongTermDays: 30         # Période plus courte
  
  atrSpikeThreshold: 1.1           # Seuil plus bas
  atrShortTermDays: 3              # Période plus courte
  atrLongTermDays: 15              # Période plus courte
  
  priceStdShortTermDays: 3         # Période plus courte
  priceStdLongTermDays: 30         # Période plus courte
  priceStdSpikeThreshold: 1.05     # Seuil plus bas
  
  volatilityFiltersPassingThreshold: 1  # Au moins 1 filtre au lieu de 2
  
  # Filtres de droite (breakout)
  breakoutDetectionDaysLookback: 10      # Réduit de 20 à 10
  breakoutDetectionPriceRatioThreshold: 0.03  # Seuil plus bas
  breakoutDetectionMaTolerance: 1.0
  breakoutDetectionVolumeAugmentationRatioThreshold: 1.2  # Seuil plus bas
  
  structureConfirmationDaysLookback: 10  # Réduit de 20 à 10
  structureConfirmationMaTolerance: 0.95
  
  bestTargetsN: 50  # Plus de cibles pour avoir plus de résultats

# Configuration du site statique
website:
  title: "🐾 ChaseHound - Analyse Automatisée"
  description: "Résultats d'analyse boursière générés automatiquement"
  refresh_interval_hours: 24  # Mise à jour quotidienne
  
# Configuration des notifications (optionnel)
notifications:
  enabled: false
  webhook_url: ""  # URL Discord/Slack pour notifications 